version: '3.7'

services:
   database:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: database
       MYSQL_USER: main
       MYSQL_PASSWORD: password

   wordpress:
     depends_on:
       - database
     image: wordpress:latest
     ports:
       - "8088:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: database:3306
       WORDPRESS_DB_USER: main
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: database